/* rti2code: autogenerated libFAUDES rti registration: libFAUDES 2.33m timed-iodevice-simulator */

namespace faudes {
/* Auto-register faudes types */
AutoRegisterType<Alphabet> gRti1RegisterAlphabet("Alphabet");
AutoRegisterElementTag<Alphabet> gRti1ElementTagAlphabet("Alphabet", "Event");
AutoRegisterType<xDevice> gRti5RegisterDeviceContainer("DeviceContainer");
AutoRegisterType<EventSet> gRti7RegisterEventSet("EventSet");
AutoRegisterElementTag<EventSet> gRti7ElementTagEventSet("EventSet", "Event");
AutoRegisterType<EventSetVector> gRti8RegisterEventSetVector("EventSetVector");
AutoRegisterElementTag<EventSetVector> gRti8ElementTagEventSetVector("EventSetVector", "EventSet");
AutoRegisterElementType<EventSetVector> gRti8ElementTypeEventSetVector("EventSetVector", "EventSet");
AutoRegisterType<Generator> gRti9RegisterGenerator("Generator");
AutoRegisterType<GeneratorVector> gRti10RegisterGeneratorVector("GeneratorVector");
AutoRegisterElementTag<GeneratorVector> gRti10ElementTagGeneratorVector("GeneratorVector", "Generator");
AutoRegisterElementType<GeneratorVector> gRti10ElementTypeGeneratorVector("GeneratorVector", "Generator");
AutoRegisterType<ProductCompositionMap> gRti16RegisterProductCompositionMap("ProductCompositionMap");
AutoRegisterType<RelabelMap> gRti18RegisterRelabelMap("RelabelMap");
AutoRegisterElementTag<RelabelMap> gRti18ElementTagRelabelMap("RelabelMap", "Label");
AutoRegisterType<sEventSet> gRti21RegisterSimulationAlphabet("SimulationAlphabet");
AutoRegisterElementTag<sEventSet> gRti21ElementTagSimulationAlphabet("SimulationAlphabet", "Event");
AutoRegisterType<SimConditionSet> gRti22RegisterSimulationConditions("SimulationConditions");
AutoRegisterElementTag<SimConditionSet> gRti22ElementTagSimulationConditions("SimulationConditions", "Condition");
AutoRegisterType<StateSet> gRti24RegisterStateSet("StateSet");
AutoRegisterElementTag<StateSet> gRti24ElementTagStateSet("StateSet", "State");
AutoRegisterType<System> gRti26RegisterSystem("System");
AutoRegisterType<SystemVector> gRti27RegisterSystemVector("SystemVector");
AutoRegisterElementTag<SystemVector> gRti27ElementTagSystemVector("SystemVector", "Generator");
AutoRegisterElementType<SystemVector> gRti27ElementTypeSystemVector("SystemVector", "System");
AutoRegisterType<TransSet> gRti28RegisterTransSet("TransSet");
AutoRegisterElementTag<TransSet> gRti28ElementTagTransSet("TransSet", "Tr");
} // namespace
namespace faudes {
/* Register faudes types */
void LoadRegisteredTypes(void) {
  TypeRegistry::G()->Insert<Alphabet>("Alphabet");
  TypeRegistry::G()->Insert<Boolean>("Boolean");
  TypeRegistry::G()->Insert<xDevice>("DeviceContainer");
  TypeRegistry::G()->Insert<DeviceExecutor>("DeviceExecutor");
  TypeRegistry::G()->Insert<EventSet>("EventSet");
  TypeRegistry::G()->Insert<EventSetVector>("EventSetVector");
  TypeRegistry::G()->Insert<Generator>("Generator");
  TypeRegistry::G()->Insert<GeneratorVector>("GeneratorVector");
  TypeRegistry::G()->Insert<Integer>("Integer");
  TypeRegistry::G()->Insert<IntegerVector>("IntegerVector");
  TypeRegistry::G()->Insert<LoggingExecutor>("LoggingExecutor");
  TypeRegistry::G()->Insert<ParallelExecutor>("ParallelExecutor");
  TypeRegistry::G()->Insert<ProductCompositionMap>("ProductCompositionMap");
  TypeRegistry::G()->Insert<ProposingExecutor>("ProposingExecutor");
  TypeRegistry::G()->Insert<RelabelMap>("RelabelMap");
  TypeRegistry::G()->Insert<sEventSet>("SimulationAlphabet");
  TypeRegistry::G()->Insert<SimConditionSet>("SimulationConditions");
  TypeRegistry::G()->Insert<StateSet>("StateSet");
  TypeRegistry::G()->Insert<String>("String");
  TypeRegistry::G()->Insert<System>("System");
  TypeRegistry::G()->Insert<SystemVector>("SystemVector");
  TypeRegistry::G()->Insert<TransSet>("TransSet");
}
} // namespace
namespace faudes {
/* Register faudes functions */
void LoadRegisteredFunctions(void) {
  FunctionRegistry::G()->Insert<Rti0Accessible>("Accessible");
  FunctionRegistry::G()->Insert<Rti1SetDifference>("AlphabetDifference");
  FunctionRegistry::G()->Insert<Rti2SetEquality>("AlphabetEquality");
  FunctionRegistry::G()->Insert<Rti3AlphabetExtract>("AlphabetExtract");
  FunctionRegistry::G()->Insert<Rti4SetInclusion>("AlphabetInclusion");
  FunctionRegistry::G()->Insert<Rti5SetIntersection>("AlphabetIntersection");
  FunctionRegistry::G()->Insert<Rti6AlphabetLanguage>("AlphabetLanguage");
  FunctionRegistry::G()->Insert<Rti7SetUnion>("AlphabetUnion");
  FunctionRegistry::G()->Insert<Rti8ApplyRelabelMap>("ApplyRelabelMap");
  FunctionRegistry::G()->Insert<Rti9Automaton>("Automaton");
  FunctionRegistry::G()->Insert<Rti10Coaccessible>("Coaccessible");
  FunctionRegistry::G()->Insert<Rti11Complete>("Complete");
  FunctionRegistry::G()->Insert<Rti12aDeterministic>("Deterministic");
  FunctionRegistry::G()->Insert<Rti13EmptyLanguage>("EmptyLanguage");
  FunctionRegistry::G()->Insert<Rti14EmptyStringLanguage>("EmptyStringLanguage");
  FunctionRegistry::G()->Insert<Rti15FullLanguage>("FullLanguage");
  FunctionRegistry::G()->Insert<Rti16IntegerSum>("IntegerSum");
  FunctionRegistry::G()->Insert<Rti17aInvProject>("InvProject");
  FunctionRegistry::G()->Insert<Rti18IsAccessible>("IsAccessible");
  FunctionRegistry::G()->Insert<Rti19IsClosed>("IsClosed");
  FunctionRegistry::G()->Insert<Rti20IsCoaccessible>("IsCoaccessible");
  FunctionRegistry::G()->Insert<Rti21IsComplete>("IsComplete");
  FunctionRegistry::G()->Insert<Rti22IsDeterministic>("IsDeterministic");
  FunctionRegistry::G()->Insert<Rti23IsEmptyLanguage>("IsEmptyLanguage");
  FunctionRegistry::G()->Insert<Rti24IsNonblocking>("IsNonblocking");
  FunctionRegistry::G()->Insert<Rti25IsTrim>("IsTrim");
  FunctionRegistry::G()->Insert<Rti26KleeneClosure>("KleeneClosure");
  FunctionRegistry::G()->Insert<Rti27LanguageComplement>("LanguageComplement");
  FunctionRegistry::G()->Insert<Rti28LanguageConcatenate>("LanguageConcatenate");
  FunctionRegistry::G()->Insert<Rti29LanguageDifference>("LanguageDifference");
  FunctionRegistry::G()->Insert<Rti30LanguageDisjoint>("LanguageDisjoint");
  FunctionRegistry::G()->Insert<Rti31LanguageEquality>("LanguageEquality");
  FunctionRegistry::G()->Insert<Rti32LanguageInclusion>("LanguageInclusion");
  FunctionRegistry::G()->Insert<Rti33LanguageIntersection>("LanguageIntersection");
  FunctionRegistry::G()->Insert<Rti34LanguageUnion>("LanguageUnion");
  FunctionRegistry::G()->Insert<Rti35MarkAllStates>("MarkAllStates");
  FunctionRegistry::G()->Insert<Rti36aParallel>("Parallel");
  FunctionRegistry::G()->Insert<Rti37ParallelLive>("ParallelLive");
  FunctionRegistry::G()->Insert<Rti38PrefixClosure>("PrefixClosure");
  FunctionRegistry::G()->Insert<Rti39aProduct>("Product");
  FunctionRegistry::G()->Insert<Rti40aProject>("Project");
  FunctionRegistry::G()->Insert<Rti41SelfLoop>("SelfLoop");
  FunctionRegistry::G()->Insert<Rti42aStateMin>("StateMin");
  FunctionRegistry::G()->Insert<Rti43Trim>("Trim");
  FunctionRegistry::G()->Insert<Rti44UniqueInit>("UniqueInit");
}
} // namespace
